### ISSUE TITLE
Staticman integration for blog comments

### ISSUE THREAD

**Issue by okyang** [zotbins/zbceblog#2]
Integrate comment feature on the blog with static man https://staticman.net/

**Comment by okyang** [comment]
Staticman no longer hosts a public instance because they received too much traffic according to this [issue](https://github.com/eduardoboucas/staticman/issues/343#issuecomment-605256248)

Instead, we'll need to host it on our own Heroku App according to this [guide](https://travisdowns.github.io/blog/2020/02/05/now-with-comments.html)

**Comment by jessechong** [comment]
Thanks for the info. Will take a look.

**Comment by okyang** [comment]
Decided to just use Disqus instead. Decided it was not worth the time trying to figure out Staticman when the code is already setup for Disqus. But maybe in the future we will support open source and adopt Staticman instead.
