### ISSUE TITLE
Jan 2021 Typo

### ISSUE THREAD

**Issue by jessechong** [zotbins/zbceblog#3]
https://github.com/zotbins/zbceblog/blob/master/_posts/2021-1-28-january2021update.md#applying-gamification-with-apis-

"...where we try to education users..." <-- should be educate

![image](https://user-images.githubusercontent.com/44284982/106245550-78e83b80-61c1-11eb-80da-c0d3ddf3008e.png)

**Comment by okyang** [comment]
wow, I saw this just now.
